jQuery(function(b){function f(a){c>h&&(b("#estorm_gallery_smallimg ul").animate({left:-(a*g)},500),b("#estorm_gallery_smallimg_flow").animate({left:(b("#estorm_gallery_smallimg_scrollbar").width()-j)*a*g/((c-h)*g)},100))}function d(a){a<=c-h&&f(a);var d=b("#estorm_gallery_bigimg"),g=d.find("img"),j=b("#estorm_gallery_smallimg_list li").eq(a),i=j.find("img")[0],k=new Image;k.src=i.src;b(k).load(function(){var a=m,c=k.width,f=k.height;c<=a?(g.width(c).height(f),d.width(700).height(f),b("#estorm_gallery_bigimg_prev, #estorm_gallery_bigimg_next").css("top",
(f-e)/2)):(c=parseInt(a*f/c),g.width(a).height(c),d.width(a).height(c),b("#estorm_gallery_bigimg_prev, #estorm_gallery_bigimg_next").css("top",(c-e)/2));g.attr("src",i.src);i.alt&&b("#estorm_gallery_intro").html(i.alt);j.addClass("curr").siblings("li").removeClass("curr")})}var m=700,e=110,a=0,c=b("#estorm_gallery_smallimg li").length,g=89,h=7;Math.ceil(c/h);for(var j=70,i=!1,l;b("#estorm_gallery_smallimg_list ul li")[0];){b("#estorm_gallery_smallimg_list ul").width(c*g);d(a);break}b("#estorm_gallery_bigimg_prev").click(function(){a-=
1;0<=a||(a=c-1);d(a)});b("#estorm_gallery_bigimg_next").click(function(){a+=1;a<c||(a=0);d(a)});b("#estorm_gallery_smallimg_list li").click(function(){a=b("#estorm_gallery_smallimg_list li").index(this);d(a);b(this).addClass("curr").siblings("li").removeClass("curr")});b("#estorm_gallery_smallimg_arrleft").click(function(){a-=h;0>a&&(a=0);f(a)});b("#estorm_gallery_smallimg_arright").click(function(){a+=h;a>c-h&&(a=c-h);f(a)});c>h&&b("#estorm_gallery_smallimg_flow").dragDrop({fixarea:[0,b("#estorm_gallery_smallimg_scrollbar").width()-
j,0,b("#estorm_gallery_smallimg_scrollbar").height()-j],dragDirection:"horizontal",callback:function(d){a=parseInt(d.moveX*(c-h)*g/((b("#estorm_gallery_smallimg_scrollbar").width()-j)*g));b("#estorm_gallery_smallimg ul").css({left:-(a*g)})}});b("#estorm_gallery_auto a").click(function(){!1==i?(b(this).text("\u505c\u6b62\u64ad\u653e"),i=!0,l=setInterval(function(){d(a);a++;a==c&&(a=0)},3E3)):!0==i&&(b(this).text("\u81ea\u52a8\u64ad\u653e"),i=!1,l&&clearInterval(l))});b(window).keydown(function(b){switch(b.which){case 37:a-=
1;0<=a||(a=c-1);d(a);break;case 39:a+=1,a<c||(a=0),d(a)}})});
(function(b){b.extend({mouseCoords:function(b){return b.pageX||b.pageY?{x:b.pageX,y:b.pageY}:{x:b.clientX+document.body.scrollLeft-document.body.clientLeft,y:b.clientY+document.body.scrollTop-document.body.clientTop}},getStyle:function(b,d){return b.currentStyle?b.currentStyle[d]:document.defaultView.getComputedStyle(b,null)[d]}});b.fn.dragDrop=function(f){var d=b.extend({},b.fn.dragDrop.defaults,f);return this.each(function(){var f=!1,e=b(this),a=d.focuEle?b(d.focuEle,e):e;if(!a||0>=a.length)return alert("focuEle is not found! the element must be a child of "+
this.id),!1;var c={initDiffX:"",initDiffY:"",moveX:"",moveY:""};e.css({position:"absolute",left:"0",top:"0"});a.bind("mousedown",function(a){f=!0;e.css({cursor:"move"});e.get(0).setCapture&&e.get(0).setCapture();c.initDiffX=b.mouseCoords(a).x-e.position().left;c.initDiffY=b.mouseCoords(a).y-e.position().top});a.bind("mousemove",function(a){if(f){c.moveX=b.mouseCoords(a).x-c.initDiffX;c.moveY=b.mouseCoords(a).y-c.initDiffY;if(d.fixarea&&(c.moveX<d.fixarea[0]&&(c.moveX=d.fixarea[0]),c.moveX>d.fixarea[1]&&
(c.moveX=d.fixarea[1]),c.moveY<d.fixarea[2]&&(c.moveY=d.fixarea[2]),c.moveY>d.fixarea[3]))c.moveY=d.fixarea[3];"all"==d.dragDirection?e.css({left:c.moveX,top:c.moveY}):"vertical"==d.dragDirection?e.css({top:c.moveY}):"horizontal"==d.dragDirection&&e.css({left:c.moveX});d.callback&&d.callback.call(d.callback,c)}});a.bind("mouseup",function(){f=!1;e.css({cursor:"default"});e.get(0).releaseCapture&&e.get(0).releaseCapture()})})};b.fn.dragDrop.defaults={focuEle:null,callback:null,dragDirection:"all",
fixarea:null}})(jQuery);
